/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityTotal } from './activityTotal';


/**
 * A set of rolled-up statistics and totals for an athlete
 */
export interface ActivityStats { 
    /**
     * The longest distance ridden by the athlete.
     */
    biggestRideDistance?: number;
    /**
     * The highest climb ridden by the athlete.
     */
    biggestClimbElevationGain?: number;
    /**
     * The recent (last 4 weeks) ride stats for the athlete.
     */
    recentRideTotals?: ActivityTotal;
    /**
     * The recent (last 4 weeks) run stats for the athlete.
     */
    recentRunTotals?: ActivityTotal;
    /**
     * The recent (last 4 weeks) swim stats for the athlete.
     */
    recentSwimTotals?: ActivityTotal;
    /**
     * The year to date ride stats for the athlete.
     */
    ytdRideTotals?: ActivityTotal;
    /**
     * The year to date run stats for the athlete.
     */
    ytdRunTotals?: ActivityTotal;
    /**
     * The year to date swim stats for the athlete.
     */
    ytdSwimTotals?: ActivityTotal;
    /**
     * The all time ride stats for the athlete.
     */
    allRideTotals?: ActivityTotal;
    /**
     * The all time run stats for the athlete.
     */
    allRunTotals?: ActivityTotal;
    /**
     * The all time swim stats for the athlete.
     */
    allSwimTotals?: ActivityTotal;
}
