/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityType } from './activityType';
import { SummaryClub } from './summaryClub';


export interface DetailedClub extends SummaryClub { 
    /**
     * The membership status of the logged-in athlete.
     */
    membership?: DetailedClub.MembershipEnum;
    /**
     * Whether the currently logged-in athlete is an administrator of this club.
     */
    admin?: boolean;
    /**
     * Whether the currently logged-in athlete is the owner of this club.
     */
    owner?: boolean;
    /**
     * The number of athletes in the club that the logged-in athlete follows.
     */
    followingCount?: number;
}
export namespace DetailedClub {
    export type MembershipEnum = 'member' | 'pending';
    export const MembershipEnum = {
        Member: 'member' as MembershipEnum,
        Pending: 'pending' as MembershipEnum
    };
}
