/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SummaryAthlete } from './summaryAthlete';
import { SummaryClub } from './summaryClub';
import { SummaryGear } from './summaryGear';


export interface DetailedAthlete extends SummaryAthlete { 
    /**
     * The athlete's follower count.
     */
    followerCount?: number;
    /**
     * The athlete's friend count.
     */
    friendCount?: number;
    /**
     * The athlete's preferred unit system.
     */
    measurementPreference?: DetailedAthlete.MeasurementPreferenceEnum;
    /**
     * The athlete's FTP (Functional Threshold Power).
     */
    ftp?: number;
    /**
     * The athlete's weight.
     */
    weight?: number;
    /**
     * The athlete's clubs.
     */
    clubs?: Array<SummaryClub>;
    /**
     * The athlete's bikes.
     */
    bikes?: Array<SummaryGear>;
    /**
     * The athlete's shoes.
     */
    shoes?: Array<SummaryGear>;
}
export namespace DetailedAthlete {
    export type MeasurementPreferenceEnum = 'feet' | 'meters';
    export const MeasurementPreferenceEnum = {
        Feet: 'feet' as MeasurementPreferenceEnum,
        Meters: 'meters' as MeasurementPreferenceEnum
    };
}
