/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityType } from './activityType';
import { DetailedSegmentEffort } from './detailedSegmentEffort';
import { Lap } from './lap';
import { LatLng } from './latLng';
import { MetaAthlete } from './metaAthlete';
import { PhotosSummary } from './photosSummary';
import { PolylineMap } from './polylineMap';
import { Split } from './split';
import { SportType } from './sportType';
import { SummaryActivity } from './summaryActivity';
import { SummaryGear } from './summaryGear';


export interface DetailedActivity extends SummaryActivity { 
    /**
     * The description of the activity
     */
    description?: string;
    photos?: PhotosSummary;
    gear?: SummaryGear;
    /**
     * The number of kilocalories consumed during this activity
     */
    calories?: number;
    segmentEfforts?: Array<DetailedSegmentEffort>;
    /**
     * The name of the device used to record the activity
     */
    deviceName?: string;
    /**
     * The token used to embed a Strava activity
     */
    embedToken?: string;
    /**
     * The splits of this activity in metric units (for runs)
     */
    splitsMetric?: Array<Split>;
    /**
     * The splits of this activity in imperial units (for runs)
     */
    splitsStandard?: Array<Split>;
    laps?: Array<Lap>;
    bestEfforts?: Array<DetailedSegmentEffort>;
}
