/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)
 */
export type SportType = 'AlpineSki' | 'BackcountrySki' | 'Badminton' | 'Basketball' | 'Canoeing' | 'Cricket' | 'Crossfit' | 'Dance' | 'EBikeRide' | 'Elliptical' | 'EMountainBikeRide' | 'Golf' | 'GravelRide' | 'Handcycle' | 'HighIntensityIntervalTraining' | 'Hike' | 'IceSkate' | 'InlineSkate' | 'Kayaking' | 'Kitesurf' | 'MountainBikeRide' | 'NordicSki' | 'Padel' | 'PhysicalTherapy' | 'Pickleball' | 'Pilates' | 'Racquetball' | 'Ride' | 'RockClimbing' | 'RollerSki' | 'Rowing' | 'Run' | 'Sail' | 'Skateboard' | 'Snowboard' | 'Snowshoe' | 'Soccer' | 'Squash' | 'StairStepper' | 'StandUpPaddling' | 'Surfing' | 'Swim' | 'TableTennis' | 'Tennis' | 'TrailRun' | 'Velomobile' | 'VirtualRide' | 'VirtualRow' | 'VirtualRun' | 'Volleyball' | 'Walk' | 'WeightTraining' | 'Wheelchair' | 'Windsurf' | 'Workout' | 'Yoga';

export const SportType = {
    AlpineSki: 'AlpineSki' as SportType,
    BackcountrySki: 'BackcountrySki' as SportType,
    Badminton: 'Badminton' as SportType,
    Basketball: 'Basketball' as SportType,
    Canoeing: 'Canoeing' as SportType,
    Cricket: 'Cricket' as SportType,
    Crossfit: 'Crossfit' as SportType,
    Dance: 'Dance' as SportType,
    EBikeRide: 'EBikeRide' as SportType,
    Elliptical: 'Elliptical' as SportType,
    EMountainBikeRide: 'EMountainBikeRide' as SportType,
    Golf: 'Golf' as SportType,
    GravelRide: 'GravelRide' as SportType,
    Handcycle: 'Handcycle' as SportType,
    HighIntensityIntervalTraining: 'HighIntensityIntervalTraining' as SportType,
    Hike: 'Hike' as SportType,
    IceSkate: 'IceSkate' as SportType,
    InlineSkate: 'InlineSkate' as SportType,
    Kayaking: 'Kayaking' as SportType,
    Kitesurf: 'Kitesurf' as SportType,
    MountainBikeRide: 'MountainBikeRide' as SportType,
    NordicSki: 'NordicSki' as SportType,
    Padel: 'Padel' as SportType,
    PhysicalTherapy: 'PhysicalTherapy' as SportType,
    Pickleball: 'Pickleball' as SportType,
    Pilates: 'Pilates' as SportType,
    Racquetball: 'Racquetball' as SportType,
    Ride: 'Ride' as SportType,
    RockClimbing: 'RockClimbing' as SportType,
    RollerSki: 'RollerSki' as SportType,
    Rowing: 'Rowing' as SportType,
    Run: 'Run' as SportType,
    Sail: 'Sail' as SportType,
    Skateboard: 'Skateboard' as SportType,
    Snowboard: 'Snowboard' as SportType,
    Snowshoe: 'Snowshoe' as SportType,
    Soccer: 'Soccer' as SportType,
    Squash: 'Squash' as SportType,
    StairStepper: 'StairStepper' as SportType,
    StandUpPaddling: 'StandUpPaddling' as SportType,
    Surfing: 'Surfing' as SportType,
    Swim: 'Swim' as SportType,
    TableTennis: 'TableTennis' as SportType,
    Tennis: 'Tennis' as SportType,
    TrailRun: 'TrailRun' as SportType,
    Velomobile: 'Velomobile' as SportType,
    VirtualRide: 'VirtualRide' as SportType,
    VirtualRow: 'VirtualRow' as SportType,
    VirtualRun: 'VirtualRun' as SportType,
    Volleyball: 'Volleyball' as SportType,
    Walk: 'Walk' as SportType,
    WeightTraining: 'WeightTraining' as SportType,
    Wheelchair: 'Wheelchair' as SportType,
    Windsurf: 'Windsurf' as SportType,
    Workout: 'Workout' as SportType,
    Yoga: 'Yoga' as SportType
};
