/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SummaryPRSegmentEffort { 
    /**
     * The unique identifier of the activity related to the PR effort.
     */
    prActivityId?: number;
    /**
     * The elapsed time ot the PR effort.
     */
    prElapsedTime?: number;
    /**
     * The time at which the PR effort was started.
     */
    prDate?: Date;
    /**
     * Number of efforts by the authenticated athlete on this segment.
     */
    effortCount?: number;
}
