/**
 * Strava API v3
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityType } from './activityType';
import { MetaClub } from './metaClub';


export interface SummaryClub extends MetaClub { 
    /**
     * URL to a 60x60 pixel profile picture.
     */
    profileMedium?: string;
    /**
     * URL to a ~1185x580 pixel cover photo.
     */
    coverPhoto?: string;
    /**
     * URL to a ~360x176  pixel cover photo.
     */
    coverPhotoSmall?: string;
    /**
     * Deprecated. Prefer to use activity_types.
     */
    sportType?: SummaryClub.SportTypeEnum;
    /**
     * The activity types that count for a club. This takes precedence over sport_type.
     */
    activityTypes?: Array<ActivityType>;
    /**
     * The club's city.
     */
    city?: string;
    /**
     * The club's state or geographical region.
     */
    state?: string;
    /**
     * The club's country.
     */
    country?: string;
    /**
     * Whether the club is private.
     */
    _private?: boolean;
    /**
     * The club's member count.
     */
    memberCount?: number;
    /**
     * Whether the club is featured or not.
     */
    featured?: boolean;
    /**
     * Whether the club is verified or not.
     */
    verified?: boolean;
    /**
     * The club's vanity URL.
     */
    url?: string;
}
export namespace SummaryClub {
    export type SportTypeEnum = 'cycling' | 'running' | 'triathlon' | 'other';
    export const SportTypeEnum = {
        Cycling: 'cycling' as SportTypeEnum,
        Running: 'running' as SportTypeEnum,
        Triathlon: 'triathlon' as SportTypeEnum,
        Other: 'other' as SportTypeEnum
    };
}
